// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDNKTllE7RqcbCinZWDxmiAqIXoyHkvZrE',
    appId: '1:729451382665:web:1270f95ceda187d72ec358',
    messagingSenderId: '729451382665',
    projectId: 'academiamusica-bd09b',
    authDomain: 'academiamusica-bd09b.firebaseapp.com',
    storageBucket: 'academiamusica-bd09b.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDiE1hVVMey1a0XFSwaQKluBCRCenKP5d4',
    appId: '1:729451382665:android:c476f76c20d1172f2ec358',
    messagingSenderId: '729451382665',
    projectId: 'academiamusica-bd09b',
    storageBucket: 'academiamusica-bd09b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAhY3blz-nY0jflwB7dBtuGlxRIzu36Ixw',
    appId: '1:729451382665:ios:722b85d3644d891c2ec358',
    messagingSenderId: '729451382665',
    projectId: 'academiamusica-bd09b',
    storageBucket: 'academiamusica-bd09b.firebasestorage.app',
    iosBundleId: 'com.example.academiaMusica',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAhY3blz-nY0jflwB7dBtuGlxRIzu36Ixw',
    appId: '1:729451382665:ios:722b85d3644d891c2ec358',
    messagingSenderId: '729451382665',
    projectId: 'academiamusica-bd09b',
    storageBucket: 'academiamusica-bd09b.firebasestorage.app',
    iosBundleId: 'com.example.academiaMusica',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDNKTllE7RqcbCinZWDxmiAqIXoyHkvZrE',
    appId: '1:729451382665:web:308c0397ed78a4912ec358',
    messagingSenderId: '729451382665',
    projectId: 'academiamusica-bd09b',
    authDomain: 'academiamusica-bd09b.firebaseapp.com',
    storageBucket: 'academiamusica-bd09b.firebasestorage.app',
  );

}